name: 'Test with Coverage, Build and Publish'
description: 'Test a Python application, generate coverage report, build and publish the package.'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
  ruff-args:
    description: 'Extra arguments to pass to ruff'
    required: false
    default: '--line-length=120'
  sync-args:
    description: 'Extra arguments to pass to uv install'
    required: false
    default: ''
  pytest-args:
    description: 'Extra arguments to pass to pytest'
    required: false
  pypi-token: # For publishing to PyPI
    description: 'PyPI API token'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: deeprave/actions/test-build-with-cov@main
      with:
        python-version: ${{ inputs.python-version }}
        ruff-args: ${{ inputs.ruff-args }}
        sync-args: ${{ inputs.sync-args }}
        pytest-args: ${{ inputs.pytest-args }}

    - name: Publish package
      shell: bash
      run: uv publish --token ${{ inputs.pypi-token }} # Or appropriate token variable.
