name: 'Test with Coverage and Build'
description: 'Test a Python application, generate coverage report and build the package.'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
  ruff-args:
    description: 'Extra arguments to pass to ruff'
    required: false
    default: '--line-length=120'
  sync-args:
    description: 'Extra arguments to pass to uv install'
    required: false
    default: ''
  pytest-args:
    description: 'Extra arguments to pass to pytest'
    required: false

runs:
  using: 'composite'
  steps:  
    - uses: ./test
      with:
        python-version: ${{ inputs.python-version }}
        ruff-args: ${{ inputs.ruff-args }}
        sync-args: ${{ inputs.sync-args }}
        pytest-args: ${{ inputs.pytest-args }}

    - name: Build package
      shell: bash
      run: uv build

